import Link from 'next/link';
//npm install @next/font
import { Roboto } from "next/font/google";
import './globals.css'
import { MyRoutes } from './interfaces/layout.interfaces';
import NavigationComponent from './components/Navigation';

export const metadata = {
  title: 'Petland',
  description: 'Generated by create next app',
}


//Esto se puede hacer en un font.js y exportar fonts
const fonts = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={fonts.className} >
        <NavigationComponent></NavigationComponent>
        {children}
      </body>
    </html>
  )
}
